services:
  facilitator:
    build:
      context: ../..
      dockerfile: typescript/facilitator/Dockerfile
    ports: ["${PORT}:${PORT}"]
    volumes: [facilitator-data:/data]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PORT=${PORT}
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE}
      - KEEP_BACKUPS=${KEEP_BACKUPS}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  facilitator-data:
    name: h402-facilitator-data
