name: Publish NPM packages

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches:
      - main
    paths:
      - 'typescript/packages/h402/**'    
      - 'typescript/packages/h402-express/**'
      - 'typescript/packages/h402-fetch/**'
  push:
    paths:
      - 'typescript/packages/h402/**'
      - 'typescript/packages/h402-express/**'
      - 'typescript/packages/h402-fetch/**'

jobs:
  build:
    runs-on: [self-hosted]
    outputs:
      matrix: ${{ steps.publish-matrix.outputs.matrix }}
    strategy:
      matrix:
       package:
        - h402
        - h402-express
        - h402-fetch

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@bit-gpt"
          cache: "pnpm"

      - name: Build
        run: |
          cd ./typescript/packages/${{ matrix.package }}
          pnpm --filter '@bit-gpt/${{ matrix.package }}' i
          pnpm --filter '@bit-gpt/${{ matrix.package }}' build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-dist
          path: typescript/packages/${{ matrix.package }}/dist
          if-no-files-found: error

  publish:
    runs-on: [self-hosted]
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        package:
          - h402
          - h402-express
          - h402-fetch

    permissions:
      packages: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.package }}-dist
          path: typescript/packages/${{ matrix.package }}/dist

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Publish GitHub
        run: |
          npm config set @bit-gpt:registry https://npm.pkg.github.com -L project
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc 
          pnpm publish --filter '@bit-gpt/${{ matrix.package }}' --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish NPM
        run: |
          npm config set @bit-gpt:registry https://registry.npmjs.org -L project
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc
          pnpm publish --filter '@bit-gpt/${{ matrix.package }}' --no-git-checks --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}