name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches:
      - main
    paths:
      - 'typescript/packages/h402/**'    
  push:
    paths:
      - 'typescript/packages/h402/**'

jobs:
  build:
    runs-on: [self-hosted]

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@bit-gpt"
          cache: "pnpm"

      - name: Build
        run: |
          cd ./typescript/packages/h402
          pnpm --filter '@bit-gpt/h402' i
          pnpm --filter '@bit-gpt/h402' build
          pnpm publish --filter '@bit-gpt/h402' --no-git-checks 
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: [self-hosted]
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      packages: write
    
    steps:
      - name: Publish
        run: |
          pnpm publish --filter '@bit-gpt/h402' --no-git-checks 
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
